###
@languageId= 4921c695-dfef-40c3-8562-1d68a73aef88
@projectId= a87b37c3-28ac-4039-b3fc-700d919cf755
POST {{API_URL}}/api/projects/{{projectId}}/languages
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "English",
  "code": "en",
  "projectId": "{{projectId}}"
}

### 
GET {{API_URL}}/api/projects/{{projectId}}/languages
Authorization: Bearer {{access_token}}

### 
GET {{API_URL}}/api/projects/{{projectId}}/languages/{{languageId}}
Authorization: Bearer {{access_token}}

### 
PUT {{API_URL}}/api/projects/{{projectId}}/languages/{{languageId}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "English Updated",
  "code": "en",
  "projectId": "{{projectId}}"
}

### 
DELETE {{API_URL}}/api/projects/{{projectId}}/languages/{{languageId}}
Authorization: Bearer {{access_token}}