###
@projectId= a87b37c3-28ac-4039-b3fc-700d919cf755
POST {{API_URL}}/api/projects
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "text",
  "description": "zxczczczc",
  "baseLanguage": "0ece9af0-6547-4702-870f-a30c35b02f0e"
}

### 
GET {{API_URL}}/api/projects
Authorization: Bearer {{access_token}}

### 
GET {{API_URL}}/api/projects/{{projectId}}
Authorization: Bearer {{access_token}}


### 
PUT {{API_URL}}/api/projects/{{projectId}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Nowy projekt",
  "description": "Najważniejszy projekt",
  "baseLanguage": "ef8aa70a-7241-436d-a3ab-831d990f9d61"
}

### 
PUT {{API_URL}}/api/projects/{{projectId}}/base-language
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "languageId": "0ece9af0-6547-4702-870f-a30c35b02f0e"
}

### 
DELETE {{API_URL}}/api/budgets/{{budgetId}}/expenses/0ece9af0-6547-4702-870f-a30c35b02f0e
Authorization: Bearer {{access_token}}

