###
@translationKeyId= 7a202c5b-4755-40ba-a417-f4fd63a2c550
@projectId= a87b37c3-28ac-4039-b3fc-700d919cf755
@translationTextId= 14f5a4c1-11e5-49f2-aa2b-15a6fe83425a
POST {{API_URL}}/api/projects/{{projectId}}/translations/keys
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Greeting 21355",
  "projectId": "{{projectId}}"
}

###
GET {{API_URL}}/api/projects/{{projectId}}/translations/keys
Authorization: Bearer {{access_token}}

###
GET {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}
Authorization: Bearer {{access_token}}

###
PUT {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Greeting Updated"
}

###
DELETE {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}
Authorization: Bearer {{access_token}}


### KEYS TEXTS

###
POST {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}/texts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "value": "Hello World",
  "translationKeyId": "{{translationKeyId}}",
  "languageId": "0ece9af0-6547-4702-870f-a30c35b02f0e"
}

### 
GET {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}/texts
Authorization: Bearer {{access_token}}

###
GET {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}/texts/{{translationTextId}}
Authorization: Bearer {{access_token}}

### 
PUT {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}/texts/{{translationTextId}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "value": "Hello World Updated"
}

###
DELETE {{API_URL}}/api/projects/{{projectId}}/translations/keys/{{translationKeyId}}/texts/{{translationTextId}}
Authorization: Bearer {{access_token}}

